<?php

namespace Database\Seeders;

use App\Models\FixDetail;
use Illuminate\Database\Seeder;

class FixDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'フロントパネル交換/SC'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'フロントパネル交換/RP'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'フロントパネル交換/RW'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'フロントパネル交換/OR'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'バッテリー交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'バッテリー交換/大容量'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>1,
          'name'=>'バッテリーシール'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>1,
          'name'=>'防水シール'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>1,
          'name'=>'コーティング'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>1,
          'name'=>'内部クリーニング'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>1,
          'name'=>'強化ガラス'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'点検/作業'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'水没洗浄'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'バックパネル交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'外装交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'充電コネクター交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'イヤホンジャック交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'ホームボタン交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'パワーセンサーケーブル交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'インダクションケーブル交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'イヤースピーカー交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'ライドスピーカー交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'バイブレーター交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'アウトカメラ交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'インカメラ交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'マナーボタン交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'ボリュームボタン交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'スリープボタン交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'wifiアンテナ交換'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'フレーム矯正'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'リンゴループ修理'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'クリーニング'
        ]);
        FixDetail::create([
          'status'=>1,
          'option'=>0,
          'name'=>'スマホ復旧'
        ]);
    }
}
